workflows:
  android-release:
    name: EchoWolf Android
    max_build_duration: 60

    environment:
      flutter: 3.22.0
      java: 17

    scripts:
      # Fix Windows line endings + permission
      - name: Fix gradlew
        script: |
          sed -i 's/\r$//' android/gradlew
          chmod +x android/gradlew

      - name: Get packages
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - srinathsenthil42@gmail.com
        notify:
          success: true
          failure: true
